{% set name = "types-MarkupSafe" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-MarkupSafe-{{ version }}.tar.gz
  sha256: 3c3b04062e44790f5db54959de02f737b34d760f0c4c99c41c1aef2aade0aa8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/markupsafe-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for MarkupSafe
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
